# Generated by Django 5.0.4 on 2024-05-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0009_editlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='children1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
